ALTER TYPE "FinanceScheduleType" ADD VALUE 'PROVISION';
CREATE TYPE "FxRevaluationStatus" AS ENUM ('DRAFT','PENDING_APPROVAL','POSTED','REVERSED');
CREATE TYPE "FinanceAdvanceSide" AS ENUM ('CUSTOMER','VENDOR');
ALTER TABLE "sales_invoices" ADD COLUMN "creditOverrideReason" TEXT, ADD COLUMN "creditOverrideApprovedById" TEXT, ADD COLUMN "creditOverrideApprovedAt" TIMESTAMP(3);

CREATE TABLE "customer_credit_controls" ("id" TEXT NOT NULL, "customerId" TEXT NOT NULL, "creditLimitInr" DECIMAL(18,2) NOT NULL, "overdueGraceDays" INTEGER NOT NULL DEFAULT 0, "blockOnLimit" BOOLEAN NOT NULL DEFAULT true, "blockOnOverdue" BOOLEAN NOT NULL DEFAULT true, "reviewDate" TIMESTAMP(3), "notes" TEXT, "createdById" TEXT NOT NULL, "updatedById" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "customer_credit_controls_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "customer_credit_controls_customerId_key" ON "customer_credit_controls"("customerId");

CREATE TABLE "fx_revaluation_runs" ("id" TEXT NOT NULL, "runNumber" TEXT NOT NULL, "periodId" TEXT NOT NULL, "status" "FxRevaluationStatus" NOT NULL DEFAULT 'DRAFT', "closingRates" JSONB NOT NULL, "totalGainInr" DECIMAL(18,2) NOT NULL DEFAULT 0, "totalLossInr" DECIMAL(18,2) NOT NULL DEFAULT 0, "gainAccountId" TEXT NOT NULL, "lossAccountId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "submittedById" TEXT, "submittedAt" TIMESTAMP(3), "approvedById" TEXT, "approvedAt" TIMESTAMP(3), "journalEntryId" TEXT, "reversalEntryId" TEXT, "reversedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "fx_revaluation_runs_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "fx_revaluation_runs_runNumber_key" ON "fx_revaluation_runs"("runNumber"); CREATE UNIQUE INDEX "fx_revaluation_runs_periodId_key" ON "fx_revaluation_runs"("periodId"); CREATE UNIQUE INDEX "fx_revaluation_runs_journalEntryId_key" ON "fx_revaluation_runs"("journalEntryId"); CREATE UNIQUE INDEX "fx_revaluation_runs_reversalEntryId_key" ON "fx_revaluation_runs"("reversalEntryId"); CREATE INDEX "fx_revaluation_runs_status_periodId_idx" ON "fx_revaluation_runs"("status","periodId");

CREATE TABLE "fx_revaluation_lines" ("id" TEXT NOT NULL, "runId" TEXT NOT NULL, "side" TEXT NOT NULL, "documentId" TEXT NOT NULL, "documentNumber" TEXT NOT NULL, "partyName" TEXT NOT NULL, "currencyCode" VARCHAR(3) NOT NULL, "foreignOutstanding" DECIMAL(18,2) NOT NULL, "originalRate" DECIMAL(18,6) NOT NULL, "closingRate" DECIMAL(18,6) NOT NULL, "carryingAmountInr" DECIMAL(18,2) NOT NULL, "revaluedAmountInr" DECIMAL(18,2) NOT NULL, "gainLossInr" DECIMAL(18,2) NOT NULL, CONSTRAINT "fx_revaluation_lines_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "fx_revaluation_lines_runId_side_documentId_key" ON "fx_revaluation_lines"("runId","side","documentId"); CREATE INDEX "fx_revaluation_lines_runId_currencyCode_idx" ON "fx_revaluation_lines"("runId","currencyCode"); ALTER TABLE "fx_revaluation_lines" ADD CONSTRAINT "fx_revaluation_lines_runId_fkey" FOREIGN KEY ("runId") REFERENCES "fx_revaluation_runs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "finance_advance_applications" ("id" TEXT NOT NULL, "applicationNumber" TEXT NOT NULL, "side" "FinanceAdvanceSide" NOT NULL, "sourceId" TEXT NOT NULL, "targetInvoiceId" TEXT NOT NULL, "applicationDate" TIMESTAMP(3) NOT NULL, "currencyCode" VARCHAR(3) NOT NULL, "amount" DECIMAL(18,2) NOT NULL, "exchangeRateToInr" DECIMAL(18,6) NOT NULL DEFAULT 1, "journalEntryId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "approvedById" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "finance_advance_applications_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "finance_advance_applications_applicationNumber_key" ON "finance_advance_applications"("applicationNumber"); CREATE UNIQUE INDEX "finance_advance_applications_journalEntryId_key" ON "finance_advance_applications"("journalEntryId"); CREATE INDEX "finance_advance_applications_side_sourceId_idx" ON "finance_advance_applications"("side","sourceId"); CREATE INDEX "finance_advance_applications_side_targetInvoiceId_idx" ON "finance_advance_applications"("side","targetInvoiceId");
