import { Body, Controller, Get, Param, Post } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { QmsInspectionResult } from '@prisma/client';
import { AuthenticatedUser, CurrentUser } from '../../common/decorators/current-user.decorator';
import { CompleteQmsInspectionDto, CreateQmsInspectionDto, CreateQmsPlanDto, CreateQmsTemplateDto } from './dto/qms.dto';
import { QmsService } from './qms.service';
import { AddQmsCapaActionDto, CompleteQmsCapaActionDto, ContainQmsNcrDto, CreateQmsCapaDto, CreateQmsNcrDto, DispositionQmsNcrDto, EffectivenessDto } from './dto/qms-phase2.dto';
import { CompleteQmsAuditDto, CreateQmsAuditDto, CreateQmsAuditProgramDto } from './dto/qms-phase3.dto';
import { GenerateQmsReportDto, ReviseQmsReportDto, SignQmsReportCustomerDto } from './dto/qms-phase4.dto';
import { CloseQmsComplaintDto, CreateQmsCalibrationDto, CreateQmsComplaintDto, CreateQmsEquipmentDto, InvestigateQmsComplaintDto } from './dto/qms-phase5.dto';
@ApiTags('qms') @ApiBearerAuth() @Controller('qms')
export class QmsController { constructor(private readonly s:QmsService){}
 @Get('access') access(@CurrentUser()u:AuthenticatedUser){return this.s.accessInfo(u)} @Get('dashboard') dashboard(@CurrentUser()u:AuthenticatedUser){return this.s.dashboard(u)}
 @Get('references/employees') employees(@CurrentUser()u:AuthenticatedUser){return this.s.employees(u)}
 @Get('references/customers') customers(@CurrentUser()u:AuthenticatedUser){return this.s.customers(u)}
 @Get('templates') templates(@CurrentUser()u:AuthenticatedUser){return this.s.templates(u)} @Post('templates') createTemplate(@Body()d:CreateQmsTemplateDto,@CurrentUser()u:AuthenticatedUser){return this.s.createTemplate(d,u)} @Post('templates/:id/submit') submitTemplate(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.submitTemplate(id,u)} @Post('templates/:id/approve') approveTemplate(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.approveTemplate(id,u)}
 @Post('templates/:id/revise') reviseTemplate(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.reviseTemplate(id,u)}
 @Get('plans') plans(@CurrentUser()u:AuthenticatedUser){return this.s.plans(u)} @Post('plans') createPlan(@Body()d:CreateQmsPlanDto,@CurrentUser()u:AuthenticatedUser){return this.s.createPlan(d,u)} @Post('plans/:id/submit') submitPlan(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.submitPlan(id,u)} @Post('plans/:id/approve') approvePlan(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.approvePlan(id,u)}
 @Get('inspections') inspections(@CurrentUser()u:AuthenticatedUser){return this.s.inspections(u)} @Get('inspections/:id') inspection(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.inspection(id,u)} @Post('inspections') createInspection(@Body()d:CreateQmsInspectionDto,@CurrentUser()u:AuthenticatedUser){return this.s.createInspection(d,u)} @Post('inspections/:id/complete') complete(@Param('id')id:string,@Body()d:CompleteQmsInspectionDto,@CurrentUser()u:AuthenticatedUser){return this.s.completeInspection(id,d,u)} @Post('inspections/:id/review/:result') review(@Param('id')id:string,@Param('result')r:QmsInspectionResult,@CurrentUser()u:AuthenticatedUser){return this.s.reviewInspection(id,r,u)}
 @Get('ncrs') ncrs(@CurrentUser()u:AuthenticatedUser){return this.s.ncrs(u)} @Get('ncrs/:id') ncr(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.ncr(id,u)} @Post('ncrs') createNcr(@Body()d:CreateQmsNcrDto,@CurrentUser()u:AuthenticatedUser){return this.s.createNcr(d,u)} @Post('ncrs/:id/contain') containNcr(@Param('id')id:string,@Body()d:ContainQmsNcrDto,@CurrentUser()u:AuthenticatedUser){return this.s.containNcr(id,d,u)} @Post('ncrs/:id/disposition') dispositionNcr(@Param('id')id:string,@Body()d:DispositionQmsNcrDto,@CurrentUser()u:AuthenticatedUser){return this.s.dispositionNcr(id,d,u)} @Post('ncrs/:id/capa') createCapa(@Param('id')id:string,@Body()d:CreateQmsCapaDto,@CurrentUser()u:AuthenticatedUser){return this.s.createCapa(id,d,u)}
 @Get('capas') capas(@CurrentUser()u:AuthenticatedUser){return this.s.capas(u)} @Post('capas/:id/actions') addAction(@Param('id')id:string,@Body()d:AddQmsCapaActionDto,@CurrentUser()u:AuthenticatedUser){return this.s.addCapaAction(id,d,u)} @Post('capa-actions/:id/complete') completeAction(@Param('id')id:string,@Body()d:CompleteQmsCapaActionDto,@CurrentUser()u:AuthenticatedUser){return this.s.completeCapaAction(id,d,u)} @Post('capa-actions/:id/verify') verifyAction(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.verifyCapaAction(id,u)} @Post('capas/:id/submit-effectiveness') submitEffectiveness(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.submitEffectiveness(id,u)} @Post('capas/:id/effectiveness/:effective') effectiveness(@Param('id')id:string,@Param('effective')effective:string,@Body()d:EffectivenessDto,@CurrentUser()u:AuthenticatedUser){return this.s.reviewEffectiveness(id,effective==='true',d.result,u)}
 @Get('audit-programs') auditPrograms(@CurrentUser()u:AuthenticatedUser){return this.s.auditPrograms(u)} @Post('audit-programs') createAuditProgram(@Body()d:CreateQmsAuditProgramDto,@CurrentUser()u:AuthenticatedUser){return this.s.createAuditProgram(d,u)} @Post('audit-programs/:id/submit') submitAuditProgram(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.submitAuditProgram(id,u)} @Post('audit-programs/:id/approve') approveAuditProgram(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.approveAuditProgram(id,u)}
 @Get('audits') audits(@CurrentUser()u:AuthenticatedUser){return this.s.audits(u)} @Get('audits/:id') audit(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.audit(id,u)} @Post('audits') createAudit(@Body()d:CreateQmsAuditDto,@CurrentUser()u:AuthenticatedUser){return this.s.createAudit(d,u)} @Post('audits/:id/start') startAudit(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.startAudit(id,u)} @Post('audits/:id/complete') completeAudit(@Param('id')id:string,@Body()d:CompleteQmsAuditDto,@CurrentUser()u:AuthenticatedUser){return this.s.completeAudit(id,d,u)} @Post('audits/:id/review') reviewAudit(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.reviewAudit(id,u)}
 @Get('reports') reports(@CurrentUser()u:AuthenticatedUser){return this.s.reports(u)} @Get('reports/:id') report(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.report(id,u)} @Post('reports') generateReport(@Body()d:GenerateQmsReportDto,@CurrentUser()u:AuthenticatedUser){return this.s.generateReport(d,u)} @Post('reports/:id/sign-internal') signReportInternal(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.signReportInternal(id,u)} @Post('reports/:id/sign-customer') signReportCustomer(@Param('id')id:string,@Body()d:SignQmsReportCustomerDto,@CurrentUser()u:AuthenticatedUser){return this.s.signReportCustomer(id,d,u)} @Post('reports/:id/revise') reviseReport(@Param('id')id:string,@Body()d:ReviseQmsReportDto,@CurrentUser()u:AuthenticatedUser){return this.s.reviseReport(id,d,u)}
 @Get('equipment') equipment(@CurrentUser()u:AuthenticatedUser){return this.s.equipment(u)} @Post('equipment') createEquipment(@Body()d:CreateQmsEquipmentDto,@CurrentUser()u:AuthenticatedUser){return this.s.createEquipment(d,u)} @Post('equipment/:id/calibrations') addCalibration(@Param('id')id:string,@Body()d:CreateQmsCalibrationDto,@CurrentUser()u:AuthenticatedUser){return this.s.addCalibration(id,d,u)} @Post('calibrations/:id/review/:decision') reviewCalibration(@Param('id')id:string,@Param('decision')decision:string,@CurrentUser()u:AuthenticatedUser){return this.s.reviewCalibration(id,decision==='accept',u)}
 @Get('complaints') complaints(@CurrentUser()u:AuthenticatedUser){return this.s.complaints(u)} @Post('complaints') createComplaint(@Body()d:CreateQmsComplaintDto,@CurrentUser()u:AuthenticatedUser){return this.s.createComplaint(d,u)} @Post('complaints/:id/investigate') investigateComplaint(@Param('id')id:string,@Body()d:InvestigateQmsComplaintDto,@CurrentUser()u:AuthenticatedUser){return this.s.investigateComplaint(id,d,u)} @Post('complaints/:id/close') closeComplaint(@Param('id')id:string,@Body()d:CloseQmsComplaintDto,@CurrentUser()u:AuthenticatedUser){return this.s.closeComplaint(id,d,u)}
 @Get('supplier-scorecards') supplierScorecards(@CurrentUser()u:AuthenticatedUser){return this.s.supplierScorecards(u)} @Get('analytics') analytics(@CurrentUser()u:AuthenticatedUser){return this.s.analytics(u)}
}
