'use client';
import { FormEvent, useEffect, useState } from 'react';
import { apiFetch, ApiError } from '../../../lib/api';
import { useFinanceAccess } from '../../../lib/use-finance-access';
import { Button } from '../../../components/ui/button';
import { Card, CardContent } from '../../../components/ui/card';
import { Input } from '../../../components/ui/input';
import { Select } from '../../../components/ui/select';
import { PageContainer } from '../../../components/ui/page-container';
import { PageHeader } from '../../../components/ui/page-header';
import { useToast } from '../../../components/ui/toaster';

type Return = { id: string; returnType?: string; financialYear?: string; quarter?: string; status: string; summary?: Record<string, unknown>; arn?: string; acknowledgementNo?: string };
type Due = { id: string; obligation: string; taxPeriod: string; dueDate: string; daysRemaining: number };
type Challan = { id: string; challanNumber: string; totalAmount: string; allocations: { amount: string }[] };
type Dashboard = { taxPeriod: string; gstReturns: Return[]; tdsReturns: Return[]; gstr2b: { status: string; count: number }[]; failedSubmissions: { id: string; documentType: string; errorMessage?: string; invoice: { invoiceNumber: string } }[]; dueDates: Due[]; challans: Challan[] };

export default function FilingsPage() {
  const toast = useToast(), { isAccountsHead } = useFinanceAccess();
  const [period, setPeriod] = useState(new Date().toISOString().slice(0, 7));
  const startYear = Number(period.slice(0, 4)) - (Number(period.slice(5, 7)) < 4 ? 1 : 0);
  const [fy, setFy] = useState(`${startYear}-${String(startYear + 1).slice(-2)}`);
  const [quarter, setQuarter] = useState('Q1');
  const [obligation, setObligation] = useState('GSTR1'), [dueDate, setDueDate] = useState('');
  const [bsr, setBsr] = useState(''), [serial, setSerial] = useState(''), [challanDate, setChallanDate] = useState(''), [challanTax, setChallanTax] = useState('');
  const [data, setData] = useState<Dashboard>();
  const [json, setJson] = useState('[\n  {\n    "supplierGstin": "29ABCDE1234F1Z5",\n    "invoiceNumber": "INV-001",\n    "invoiceDate": "2026-04-01",\n    "taxableAmount": 10000,\n    "cgstAmount": 900,\n    "sgstAmount": 900\n  }\n]');
  const fail = (e: unknown) => toast.error(e instanceof ApiError ? e.message : 'Operation failed');
  const load = () => apiFetch<Dashboard>(`/finance/filings/dashboard?taxPeriod=${period}`).then(setData).catch(fail);
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  async function action(path: string, body?: object) { try { await apiFetch(path, { method: 'POST', body: JSON.stringify(body ?? {}) }); toast.success('Compliance workspace updated'); await load(); } catch (e) { fail(e); } }
  async function import2b(e: FormEvent) { e.preventDefault(); try { const lines = JSON.parse(json); await action('/finance/filings/gstr2b/import', { taxPeriod: period, lines }); } catch (x) { fail(x); } }
  async function evidence(kind: 'gst' | 'tds', id: string) { const acknowledgementNumber = window.prompt(kind === 'gst' ? 'GST ARN / acknowledgement number' : 'TDS acknowledgement number'); if (acknowledgementNumber) await action(`/finance/filings/${kind}/${id}/file-evidence`, { acknowledgementNumber }); }
  async function uploadEvidence(kind: 'GST' | 'TDS', id: string, file?: File) { if (!file) return; try { const x = await apiFetch<{ evidence: { id: string }; uploadUrl: string }>('/finance/filings/evidence/upload-url', { method: 'POST', body: JSON.stringify({ returnKind: kind, returnId: id, evidenceType: 'FILING_DOCUMENT', fileName: file.name, contentType: file.type || 'application/octet-stream' }) }); const uploaded = await fetch(x.uploadUrl, { method: 'PUT', headers: { 'content-type': file.type || 'application/octet-stream' }, body: file }); if (!uploaded.ok) throw new Error('Upload failed'); await action(`/finance/filings/evidence/${x.evidence.id}/confirm`); } catch (e) { fail(e); } }
  async function addDue(e: FormEvent) { e.preventDefault(); await action('/finance/filings/due-dates', { obligation, taxPeriod: period, dueDate }); }
  async function addChallan(e: FormEvent) { e.preventDefault(); await action('/finance/filings/tds-challans', { bsrCode: bsr, challanSerialNo: serial, depositDate: challanDate, financialYear: fy, sectionCode: 'MULTIPLE', taxAmount: Number(challanTax) }); }
  return <PageContainer>
    <PageHeader title="Statutory Filings" description="Prepare GST and TDS returns, reconcile GSTR-2B, route approval to the Finance Head, and retain filing evidence" />
    <Card className="mb-6"><CardContent className="flex flex-wrap gap-3 p-5"><Input type="month" value={period} onChange={(e) => setPeriod(e.target.value)} /><Button onClick={load}>Load period</Button><Button variant="outline" onClick={() => action(`/finance/filings/gst/GSTR1/${period}/prepare`)}>Prepare GSTR-1</Button><Button variant="outline" onClick={() => action(`/finance/filings/gst/GSTR3B/${period}/prepare`)}>Prepare GSTR-3B</Button></CardContent></Card>
    <div className="mb-6 grid gap-4 md:grid-cols-2">
      {(data?.gstReturns ?? []).map((r) => <Card key={r.id}><CardContent className="p-5"><div className="flex items-center justify-between"><div><b>{r.returnType}</b><div className="text-sm text-muted-foreground">{r.status.replaceAll('_', ' ')} {r.arn ? `· ${r.arn}` : ''}</div></div><div className="flex gap-2">{r.status === 'PREPARED' && <Button size="sm" onClick={() => action(`/finance/filings/gst/${r.id}/submit`)}>Submit</Button>}{isAccountsHead && r.status === 'PENDING_APPROVAL' && <Button size="sm" onClick={() => action(`/finance/filings/gst/${r.id}/approve`)}>Approve</Button>}{isAccountsHead && r.status === 'APPROVED' && <Button size="sm" onClick={() => evidence('gst', r.id)}>Record filing</Button>}</div></div><pre className="mt-3 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(r.summary ?? {}, null, 2)}</pre><label className="mt-3 block text-xs">Attach filing document<input className="mt-1 block" type="file" onChange={(e) => uploadEvidence('GST', r.id, e.target.files?.[0])} /></label></CardContent></Card>)}
    </div>
    <Card className="mb-6"><CardContent className="p-5"><h2 className="font-semibold">GSTR-2B Import & Reconciliation</h2><div className="my-3 flex flex-wrap gap-3">{(data?.gstr2b ?? []).map((x) => <span className="rounded border px-3 py-1 text-sm" key={x.status}>{x.status.replaceAll('_', ' ')}: {x.count}</span>)}</div><form onSubmit={import2b}><textarea className="min-h-44 w-full rounded-md border bg-background p-3 font-mono text-xs" value={json} onChange={(e) => setJson(e.target.value)} /><div className="mt-3 flex gap-2"><Button type="submit">Import portal JSON rows</Button><Button type="button" variant="outline" onClick={() => action(`/finance/filings/gstr2b/${period}/reconcile`)}>Auto-reconcile</Button></div></form></CardContent></Card>
    <Card className="mb-6"><CardContent className="p-5"><h2 className="mb-3 font-semibold">Quarterly TDS — Form 26Q</h2><div className="flex flex-wrap gap-3"><Input value={fy} onChange={(e) => setFy(e.target.value)} placeholder="2026-27" /><Select value={quarter} onChange={(e) => setQuarter(e.target.value)}><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option></Select><Button onClick={() => action(`/finance/filings/tds/${fy}/${quarter}/prepare`)}>Prepare 26Q</Button></div><div className="mt-4 space-y-2">{(data?.tdsReturns ?? []).map((r) => <div className="flex flex-wrap items-center justify-between rounded border p-3" key={r.id}><span><b>{r.financialYear} {r.quarter}</b> · {r.status.replaceAll('_', ' ')}</span><div className="flex gap-2">{r.status === 'PREPARED' && <Button size="sm" onClick={() => action(`/finance/filings/tds/${r.id}/submit`)}>Submit</Button>}{isAccountsHead && r.status === 'PENDING_APPROVAL' && <Button size="sm" onClick={() => action(`/finance/filings/tds/${r.id}/approve`)}>Approve</Button>}{isAccountsHead && r.status === 'APPROVED' && <Button size="sm" onClick={() => evidence('tds', r.id)}>Record filing / Form 16A</Button>}</div></div>)}</div></CardContent></Card>
    <div className="mb-6 grid gap-6 md:grid-cols-2"><Card><CardContent className="p-5"><h2 className="mb-3 font-semibold">Compliance Calendar</h2>{(data?.dueDates ?? []).map((x) => <div className="border-b py-2 text-sm" key={x.id}><b>{x.obligation}</b> · {x.taxPeriod} · {x.dueDate.slice(0, 10)} · {x.daysRemaining < 0 ? `${-x.daysRemaining} days overdue` : `${x.daysRemaining} days left`}</div>)}{isAccountsHead && <form className="mt-4 grid gap-2" onSubmit={addDue}><Input value={obligation} onChange={(e) => setObligation(e.target.value)} placeholder="Obligation"/><Input required type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)}/><Button type="submit">Set due date</Button></form>}</CardContent></Card><Card><CardContent className="p-5"><h2 className="mb-3 font-semibold">TDS Challans</h2>{(data?.challans ?? []).map((x) => <div className="border-b py-2 text-sm" key={x.id}>{x.challanNumber} · ₹{x.totalAmount}</div>)}<form className="mt-4 grid gap-2" onSubmit={addChallan}><Input required value={bsr} onChange={(e) => setBsr(e.target.value)} placeholder="7-digit BSR code"/><Input required value={serial} onChange={(e) => setSerial(e.target.value)} placeholder="Challan serial"/><Input required type="date" value={challanDate} onChange={(e) => setChallanDate(e.target.value)}/><Input required type="number" value={challanTax} onChange={(e) => setChallanTax(e.target.value)} placeholder="Tax amount"/><Button type="submit">Record challan</Button></form></CardContent></Card></div>
    {!!data?.failedSubmissions.length && <Card><CardContent className="p-5"><h2 className="font-semibold">Failed e-Invoice / e-Way Bill Submissions</h2>{data.failedSubmissions.map((x) => <div className="flex items-center justify-between border-b py-2 text-sm" key={x.id}><span>{x.invoice.invoiceNumber} · {x.documentType} · {x.errorMessage ?? 'Provider error'}</span>{isAccountsHead && <Button size="sm" onClick={() => action(`/finance/ar/gst-submissions/${x.id}/process`)}>Retry</Button>}</div>)}</CardContent></Card>}
    <p className="mt-4 text-xs text-muted-foreground">Preparation is based on ERP books. Filing remains manual/provider-mediated until certified portal credentials are configured; Finance Head approval and acknowledgement evidence are mandatory.</p>
  </PageContainer>;
}
