import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { PeopleProfileComponent } from './people-profile/people-profile.component';
import { AdminComponent } from './admin/admin.component';
import { ScorecardComponent } from './scorecard/scorecard.component';
import { SettingsComponent } from './settings/settings.component';
import { PeopleDirectoryComponent } from './people-directory/people-directory.component';
import { TasksComponent } from './tasks/tasks.component';
import { FinancialsComponent } from './financials/financials.component';
import { PerformanceComponent } from './performance/performance.component';
import { ReimbursementComponent } from './reimbursement/reimbursement.component';
import { ReimbursementFormComponent } from './reimbursement-form/reimbursement-form.component';
import { ComplianceTrainingComponent } from './compliance-training/compliance-training.component';
import { AssignTrainingComponent } from './assign-training/assign-training.component';
import { TrainingModuleComponent } from './training-module/training-module.component';
import { LoginComponent } from './login/login.component';
import { WorkforcePlanningComponent } from './workforce-planning/workforce-planning.component';
import { ApprovalsComponent } from './approvals/approvals.component';
import { OrgStructureComponent } from './org-structure/org-structure.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'people', component: PeopleDirectoryComponent },
  { path: 'financials', component: FinancialsComponent },
  { path: 'tasks', component: TasksComponent },
  { path: 'reimbursement', component: ReimbursementComponent },
  { path: 'reimbursement/new', component: ReimbursementFormComponent },
  { path: 'performance', component: PerformanceComponent },
  { path: 'compliance-training', component: ComplianceTrainingComponent },
  { path: 'compliance-training/:title', component: TrainingModuleComponent },
  { path: 'admin/assign-training', component: AssignTrainingComponent },
  { path: 'login', component: LoginComponent },
  { path: 'workforce-planning', component: WorkforcePlanningComponent },
  { path: 'approvals', component: ApprovalsComponent },
  { path: 'org-structure', component: OrgStructureComponent },
  { path: 'people/:id', component: PeopleProfileComponent },
  { path: 'people/:id/scorecard', component: ScorecardComponent },
  { path: 'admin', component: AdminComponent },
  { path: 'settings', component: SettingsComponent },
  { path: '**', redirectTo: '' }
];
