import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { PeopleProfileComponent } from './people-profile/people-profile.component';
import { AdminComponent } from './admin/admin.component';
import { ScorecardComponent } from './scorecard/scorecard.component';
import { TeamsComponent } from './teams/teams.component';
import { SettingsComponent } from './settings/settings.component';
import { PeopleDirectoryComponent } from './people-directory/people-directory.component';
import { TasksComponent } from './tasks/tasks.component';
import { FinancialsComponent } from './financials/financials.component';
import { PerformanceComponent } from './performance/performance.component';
import { ReimbursementComponent } from './reimbursement/reimbursement.component';
import { ReimbursementFormComponent } from './reimbursement-form/reimbursement-form.component';
import { ComplianceTrainingComponent } from './compliance-training/compliance-training.component';
import { AssignTrainingComponent } from './assign-training/assign-training.component';
import { TrainingModuleComponent } from './training-module/training-module.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'teams', component: TeamsComponent },
  { path: 'people', component: PeopleDirectoryComponent },
  { path: 'financials', component: FinancialsComponent },
  { path: 'tasks', component: TasksComponent },
  { path: 'reimbursement', component: ReimbursementComponent },
  { path: 'reimbursement/new', component: ReimbursementFormComponent },
  { path: 'performance', component: PerformanceComponent },
  { path: 'compliance-training', component: ComplianceTrainingComponent },
  { path: 'compliance-training/:title', component: TrainingModuleComponent },
  { path: 'admin/assign-training', component: AssignTrainingComponent },
  { path: 'people/:id', component: PeopleProfileComponent },
  { path: 'people/:id/scorecard', component: ScorecardComponent },
  { path: 'admin', component: AdminComponent },
  { path: 'settings', component: SettingsComponent },
  { path: '**', redirectTo: '' }
];
