'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, LayoutGrid, Plus, Rocket, Trash2 } from 'lucide-react';
import { ApiError } from '../../../lib/api';
import { useAuth } from '../../../lib/auth-context';
import {
  addActionItem,
  addAttendee,
  addMilestone,
  addRisk,
  DELIVERY_TYPE_LABEL,
  getKickoff,
  MEETING_MODE_LABEL,
  removeActionItem,
  removeAttendee,
  removeMilestone,
  removeRisk,
  updateDeliveryItem,
  updateKickoff,
  updateMilestone,
  updateRisk,
  type DeliveryType,
  type KickoffDeliveryItem,
  type KickoffMeetingMode,
  type MilestoneStatus,
  type ProjectKickoff,
  type RiskLevel,
  type RiskStatus,
} from '../../../lib/project-kickoff';
import { listMembers, type KanbanBoardMember } from '../../../lib/kanban';
import type { EmployeeSearchResult } from '../../../lib/types';
import { PageContainer } from '../../../components/ui/page-container';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/card';
import { Button } from '../../../components/ui/button';
import { Input } from '../../../components/ui/input';
import { Select } from '../../../components/ui/select';
import { Textarea } from '../../../components/ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../../../components/ui/dialog';
import { Skeleton } from '../../../components/ui/skeleton';
import { StatusBadge } from '../../../components/ui/status-badge';
import { ProcessFlow } from '../../../components/ui/process-flow';
import { kickoffFlow } from '../../../lib/record-flows';
import { EmptyState } from '../../../components/ui/empty-state';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../components/ui/table';
import { useToast } from '../../../components/ui/toaster';
import { useConfirm } from '../../../components/ui/confirm';
import { EmployeePicker } from '../../vault/_components/employee-picker';
import { KickoffPrintDocument } from '../_components/kickoff-print-document';
import { StockAvailabilitySection } from '../_components/stock-availability-section';
import { SignedConfirmationSheetCard } from '../_components/signed-confirmation-sheet-card';

function fmtDate(iso: string | null): string {
  return iso ? new Date(iso).toLocaleDateString() : '—';
}

export default function KickoffDetailPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const toast = useToast();
  const { user } = useAuth();

  const [kickoff, setKickoff] = useState<ProjectKickoff | null>(null);
  const [members, setMembers] = useState<KanbanBoardMember[]>([]);
  const [loading, setLoading] = useState(true);
  const [forbidden, setForbidden] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /**
   * Fetch the kickoff (+ board members). `showSkeleton` controls whether the
   * whole-page loading skeleton is shown: true only on the INITIAL mount. After
   * a mutation, sections call refresh() (showSkeleton=false) so the page updates
   * in place WITHOUT the skeleton early-return remounting the tree — which would
   * otherwise reset the scroll position to the top on every edit.
   */
  const fetchKickoff = useCallback(
    async (showSkeleton: boolean) => {
      if (showSkeleton) setLoading(true);
      setError(null);
      try {
        const k = await getKickoff(id);
        setKickoff(k);
        // Board members drive the action-item owner picker (owner must be a
        // board member). Best-effort — a failure just yields an empty picker.
        try {
          setMembers(await listMembers(k.kanbanBoardId));
        } catch {
          setMembers([]);
        }
      } catch (err) {
        if (err instanceof ApiError && (err.statusCode === 403 || err.statusCode === 404)) {
          setForbidden(true);
        } else {
          setError('Failed to load kickoff.');
        }
      } finally {
        if (showSkeleton) setLoading(false);
      }
    },
    [id],
  );

  // Initial load shows the skeleton; post-mutation refreshes are silent.
  const load = useCallback(() => fetchKickoff(true), [fetchKickoff]);
  const refresh = useCallback(() => fetchKickoff(false), [fetchKickoff]);

  useEffect(() => {
    void load();
  }, [load]);

  function printKickoff() {
    const previous = document.title;
    document.title = 'System generated by Workcore';
    const restore = () => {
      document.title = previous;
      window.removeEventListener('afterprint', restore);
    };
    window.addEventListener('afterprint', restore);
    window.print();
    setTimeout(restore, 1000);
  }

  if (loading) {
    return (
      <PageContainer>
        <Skeleton className="mb-4 h-6 w-24" />
        <Skeleton className="mb-6 h-9 w-72" />
        <Skeleton className="h-48 w-full" />
      </PageContainer>
    );
  }

  if (forbidden) {
    return (
      <PageContainer>
        <EmptyState
          icon={Rocket}
          title="You don’t have access to this kickoff"
          description="Only the creator, internal attendees, or a SuperAdmin can view this record."
        />
        <div className="mt-4 flex justify-center">
          <Button variant="outline" onClick={() => router.push('/project-kickoff')}>
            Back to kickoffs
          </Button>
        </div>
      </PageContainer>
    );
  }

  if (error || !kickoff) {
    return (
      <PageContainer>
        <p className="text-destructive">{error ?? 'Kickoff not found'}</p>
      </PageContainer>
    );
  }

  const canManageStatus =
    user?.role === 'SUPER_ADMIN' || kickoff.createdById === user?.sub;

  async function toggleCompleted() {
    if (!kickoff) return;
    const next = kickoff.status === 'COMPLETED' ? 'DRAFT' : 'COMPLETED';
    try {
      const updated = await updateKickoff(kickoff.id, { status: next });
      setKickoff((prev) => (prev ? { ...prev, status: updated.status } : prev));
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Failed to update status.');
    }
  }

  return (
    <>
      <KickoffPrintDocument kickoff={kickoff} />

      <PageContainer>
        <Link
          href="/project-kickoff"
          className="mb-4 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-4" /> Project Kickoff
        </Link>

        {/* ── Header ── */}
        <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
          <div>
            <div className="flex flex-wrap items-center gap-3">
              <h1 className="text-2xl font-semibold tracking-tight">
                {kickoff.projectName}
              </h1>
              <StatusBadge value={kickoff.status} />
            </div>
            <p className="mt-1 text-sm text-muted-foreground">
              <Link
                href={`/sales/orders/${kickoff.orderId}`}
                className="text-primary underline-offset-4 hover:underline"
              >
                View order
              </Link>{' '}
              · {fmtDate(kickoff.meetingDate)} ·{' '}
              {MEETING_MODE_LABEL[kickoff.meetingMode]}
              {kickoff.meetingLocation ? ` · ${kickoff.meetingLocation}` : ''}
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            {canManageStatus && (
              <Button variant="outline" onClick={toggleCompleted}>
                {kickoff.status === 'COMPLETED' ? 'Mark as Draft' : 'Mark Completed'}
              </Button>
            )}
            <Button
              variant="outline"
              onClick={() => router.push(`/kanban/boards/${kickoff.kanbanBoardId}`)}
            >
              <LayoutGrid className="size-4" /> View Project Board
            </Button>
            <Button variant="outline" onClick={printKickoff}>
              Download PDF
            </Button>
          </div>
        </div>

        {/* Live flow indicator — stage derived from status + attendee/action counts. */}
        <ProcessFlow
          title="Kickoff progress"
          className="mb-4"
          {...kickoffFlow({
            status: kickoff.status,
            attendeeCount: kickoff.attendees?.length ?? 0,
            actionItemCount: kickoff.actionItems?.length ?? 0,
          })}
        />

        <SignedConfirmationSheetCard kickoffId={kickoff.id} />
        <OverviewSection kickoff={kickoff} onSaved={(k) => setKickoff(k)} />
        <DeliveryClassificationSection kickoff={kickoff} onChanged={refresh} />
        <AttendeesSection kickoff={kickoff} onChanged={refresh} />
        <MilestonesSection kickoff={kickoff} onChanged={refresh} />
        <ActionItemsSection kickoff={kickoff} members={members} onChanged={refresh} />
        <RisksSection kickoff={kickoff} onChanged={refresh} />
        <StockAvailabilitySection kickoffId={kickoff.id} />
        <MinutesSection kickoff={kickoff} onSaved={(k) => setKickoff(k)} />
      </PageContainer>
    </>
  );
}

// ── Overview & scope ─────────────────────────────────────────────────
function OverviewSection({
  kickoff,
  onSaved,
}: {
  kickoff: ProjectKickoff;
  onSaved: (k: ProjectKickoff) => void;
}) {
  const toast = useToast();
  const [text, setText] = useState(kickoff.overviewAndScope ?? '');
  const [saving, setSaving] = useState(false);
  const dirty = text !== (kickoff.overviewAndScope ?? '');

  async function save() {
    setSaving(true);
    try {
      const updated = await updateKickoff(kickoff.id, {
        overviewAndScope: text || null,
      });
      onSaved(updated);
      toast.success('Overview saved.');
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Save failed.');
    } finally {
      setSaving(false);
    }
  }

  return (
    <Card className="mb-4">
      <CardHeader>
        <CardTitle>Overview &amp; Scope</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3 pt-0">
        <Textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          rows={4}
          placeholder="Project overview and scope…"
        />
        {dirty && (
          <Button size="sm" onClick={save} disabled={saving}>
            {saving ? 'Saving…' : 'Save'}
          </Button>
        )}
      </CardContent>
    </Card>
  );
}

// ── Attendees ────────────────────────────────────────────────────────
function AttendeesSection({
  kickoff,
  onChanged,
}: {
  kickoff: ProjectKickoff;
  onChanged: () => void;
}) {
  const toast = useToast();
  const confirm = useConfirm();
  const [mode, setMode] = useState<'none' | 'internal' | 'external'>('none');
  const [ext, setExt] = useState({
    externalName: '',
    externalOrganization: '',
    designation: '',
  });
  const [busy, setBusy] = useState(false);
  const attendees = kickoff.attendees ?? [];

  async function addInternal(e: EmployeeSearchResult) {
    setBusy(true);
    try {
      await addAttendee(kickoff.id, { employeeId: e.id, designation: undefined });
      setMode('none');
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Failed to add.');
    } finally {
      setBusy(false);
    }
  }

  async function addExternal() {
    if (!ext.externalName.trim()) return;
    setBusy(true);
    try {
      await addAttendee(kickoff.id, {
        externalName: ext.externalName.trim(),
        externalOrganization: ext.externalOrganization.trim() || undefined,
        designation: ext.designation.trim() || undefined,
      });
      setExt({ externalName: '', externalOrganization: '', designation: '' });
      setMode('none');
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Failed to add.');
    } finally {
      setBusy(false);
    }
  }

  async function remove(attendeeId: string, name: string | null) {
    if (
      !(await confirm({
        title: 'Remove attendee?',
        description: `${name ?? 'This attendee'} will be removed from the record.`,
        confirmLabel: 'Remove',
        destructive: true,
      }))
    )
      return;
    try {
      await removeAttendee(kickoff.id, attendeeId);
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Failed to remove.');
    }
  }

  return (
    <Card className="mb-4">
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <CardTitle>Attendees</CardTitle>
        <div className="flex gap-2">
          <Button size="sm" variant="outline" onClick={() => setMode('internal')}>
            <Plus className="size-4" /> Internal
          </Button>
          <Button size="sm" variant="outline" onClick={() => setMode('external')}>
            <Plus className="size-4" /> External
          </Button>
        </div>
      </CardHeader>
      <CardContent className="pt-0">
        {mode === 'internal' && (
          <div className="mb-3 rounded-md border p-3">
            <p className="mb-2 text-xs text-muted-foreground">
              Internal attendees are also added to the project board.
            </p>
            <EmployeePicker
              onSelect={addInternal}
              excludeIds={attendees
                .filter((a) => a.employeeId)
                .map((a) => a.employeeId as string)}
            />
          </div>
        )}
        {mode === 'external' && (
          <div className="mb-3 grid gap-2 rounded-md border p-3 sm:grid-cols-3">
            <Input
              placeholder="Name"
              value={ext.externalName}
              onChange={(e) => setExt({ ...ext, externalName: e.target.value })}
            />
            <Input
              placeholder="Organization"
              value={ext.externalOrganization}
              onChange={(e) =>
                setExt({ ...ext, externalOrganization: e.target.value })
              }
            />
            <Input
              placeholder="Designation"
              value={ext.designation}
              onChange={(e) => setExt({ ...ext, designation: e.target.value })}
            />
            <div className="sm:col-span-3">
              <Button size="sm" onClick={addExternal} disabled={busy || !ext.externalName.trim()}>
                Add attendee
              </Button>
            </div>
          </div>
        )}

        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Name</TableHead>
              <TableHead>Organization</TableHead>
              <TableHead>Designation</TableHead>
              <TableHead>Department</TableHead>
              <TableHead />
            </TableRow>
          </TableHeader>
          <TableBody>
            {attendees.length === 0 ? (
              <TableRow>
                <TableCell colSpan={5} className="text-center text-muted-foreground">
                  No attendees yet.
                </TableCell>
              </TableRow>
            ) : (
              attendees.map((a) => (
                <TableRow key={a.id}>
                  <TableCell className="font-medium">
                    {a.name ?? '—'}
                    {a.isInternal && (
                      <span className="ml-2 text-xs text-muted-foreground">
                        (internal)
                      </span>
                    )}
                  </TableCell>
                  <TableCell>{a.isInternal ? '—' : a.externalOrganization ?? '—'}</TableCell>
                  <TableCell>{a.designation ?? '—'}</TableCell>
                  <TableCell>{a.department ?? '—'}</TableCell>
                  <TableCell className="text-right">
                    <Button
                      variant="ghost"
                      size="icon"
                      aria-label="Remove attendee"
                      onClick={() => remove(a.id, a.name)}
                    >
                      <Trash2 className="size-4" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}

// ── Milestones ───────────────────────────────────────────────────────
const MILESTONE_STATUSES: MilestoneStatus[] = [
  'PENDING',
  'IN_PROGRESS',
  'COMPLETED',
  'DELAYED',
];

function MilestonesSection({
  kickoff,
  onChanged,
}: {
  kickoff: ProjectKickoff;
  onChanged: () => void;
}) {
  const toast = useToast();
  const confirm = useConfirm();
  const [adding, setAdding] = useState(false);
  const [form, setForm] = useState({ name: '', targetDate: '' });
  const [busy, setBusy] = useState(false);
  const milestones = kickoff.milestones ?? [];

  async function add() {
    if (!form.name.trim() || !form.targetDate) return;
    setBusy(true);
    try {
      await addMilestone(kickoff.id, {
        name: form.name.trim(),
        targetDate: form.targetDate,
      });
      setForm({ name: '', targetDate: '' });
      setAdding(false);
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Failed to add.');
    } finally {
      setBusy(false);
    }
  }

  async function setStatus(milestoneId: string, status: MilestoneStatus) {
    try {
      await updateMilestone(kickoff.id, milestoneId, { status });
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Update failed.');
    }
  }

  async function remove(milestoneId: string) {
    if (
      !(await confirm({
        title: 'Delete milestone?',
        confirmLabel: 'Delete',
        destructive: true,
      }))
    )
      return;
    try {
      await removeMilestone(kickoff.id, milestoneId);
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Delete failed.');
    }
  }

  return (
    <Card className="mb-4">
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <CardTitle>Milestones</CardTitle>
        <Button size="sm" variant="outline" onClick={() => setAdding((v) => !v)}>
          <Plus className="size-4" /> Add
        </Button>
      </CardHeader>
      <CardContent className="pt-0">
        {adding && (
          <div className="mb-3 flex flex-wrap items-end gap-2 rounded-md border p-3">
            <Input
              placeholder="Milestone name"
              value={form.name}
              onChange={(e) => setForm({ ...form, name: e.target.value })}
              className="max-w-xs"
            />
            <Input
              type="date"
              value={form.targetDate}
              onChange={(e) => setForm({ ...form, targetDate: e.target.value })}
              className="w-44"
            />
            <Button size="sm" onClick={add} disabled={busy || !form.name.trim() || !form.targetDate}>
              Add
            </Button>
          </div>
        )}
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Milestone</TableHead>
              <TableHead>Target date</TableHead>
              <TableHead>Owner</TableHead>
              <TableHead>Status</TableHead>
              <TableHead />
            </TableRow>
          </TableHeader>
          <TableBody>
            {milestones.length === 0 ? (
              <TableRow>
                <TableCell colSpan={5} className="text-center text-muted-foreground">
                  No milestones yet.
                </TableCell>
              </TableRow>
            ) : (
              milestones.map((m) => (
                <TableRow key={m.id}>
                  <TableCell className="font-medium">{m.name}</TableCell>
                  <TableCell>{fmtDate(m.targetDate)}</TableCell>
                  <TableCell>{m.ownerName ?? '—'}</TableCell>
                  <TableCell>
                    <Select
                      value={m.status}
                      onChange={(e) => setStatus(m.id, e.target.value as MilestoneStatus)}
                      className="h-8 w-40"
                    >
                      {MILESTONE_STATUSES.map((s) => (
                        <option key={s} value={s}>
                          {s.replace('_', ' ')}
                        </option>
                      ))}
                    </Select>
                  </TableCell>
                  <TableCell className="text-right">
                    <Button
                      variant="ghost"
                      size="icon"
                      aria-label="Delete milestone"
                      onClick={() => remove(m.id)}
                    >
                      <Trash2 className="size-4" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}

// ── Action items ─────────────────────────────────────────────────────
function ActionItemsSection({
  kickoff,
  members,
  onChanged,
}: {
  kickoff: ProjectKickoff;
  members: KanbanBoardMember[];
  onChanged: () => void;
}) {
  const router = useRouter();
  const toast = useToast();
  const confirm = useConfirm();
  const [adding, setAdding] = useState(false);
  const [form, setForm] = useState({ description: '', ownerId: '', dueDate: '' });
  const [busy, setBusy] = useState(false);
  const items = kickoff.actionItems ?? [];

  async function add() {
    if (!form.description.trim() || !form.ownerId) return;
    setBusy(true);
    try {
      await addActionItem(kickoff.id, {
        description: form.description.trim(),
        ownerId: form.ownerId,
        dueDate: form.dueDate || undefined,
      });
      setForm({ description: '', ownerId: '', dueDate: '' });
      setAdding(false);
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Failed to add.');
    } finally {
      setBusy(false);
    }
  }

  async function remove(actionItemId: string) {
    if (
      !(await confirm({
        title: 'Delete action item?',
        description: 'The linked board card will be archived.',
        confirmLabel: 'Delete',
        destructive: true,
      }))
    )
      return;
    try {
      await removeActionItem(kickoff.id, actionItemId);
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Delete failed.');
    }
  }

  return (
    <Card className="mb-4">
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <CardTitle>Action Items</CardTitle>
        <Button size="sm" variant="outline" onClick={() => setAdding((v) => !v)}>
          <Plus className="size-4" /> Add
        </Button>
      </CardHeader>
      <CardContent className="pt-0">
        {adding && (
          <div className="mb-3 flex flex-wrap items-end gap-2 rounded-md border p-3">
            <Input
              placeholder="Description"
              value={form.description}
              onChange={(e) => setForm({ ...form, description: e.target.value })}
              className="min-w-[240px] flex-1"
            />
            <Select
              value={form.ownerId}
              onChange={(e) => setForm({ ...form, ownerId: e.target.value })}
              className="h-9 w-52"
            >
              <option value="">Owner (board member)…</option>
              {members.map((m) => (
                <option key={m.employeeId} value={m.employeeId}>
                  {m.employeeName ?? m.employeeEmail}
                </option>
              ))}
            </Select>
            <Input
              type="date"
              value={form.dueDate}
              onChange={(e) => setForm({ ...form, dueDate: e.target.value })}
              className="w-44"
            />
            <Button size="sm" onClick={add} disabled={busy || !form.description.trim() || !form.ownerId}>
              Add
            </Button>
          </div>
        )}
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Description</TableHead>
              <TableHead>Owner</TableHead>
              <TableHead>Due date</TableHead>
              <TableHead>Status</TableHead>
              <TableHead />
            </TableRow>
          </TableHeader>
          <TableBody>
            {items.length === 0 ? (
              <TableRow>
                <TableCell colSpan={5} className="text-center text-muted-foreground">
                  No action items yet.
                </TableCell>
              </TableRow>
            ) : (
              items.map((i) => (
                <TableRow key={i.id}>
                  <TableCell className="font-medium">
                    {i.kanbanCardId ? (
                      <button
                        type="button"
                        onClick={() => router.push(`/kanban/cards/${i.kanbanCardId}`)}
                        className="text-left text-primary underline-offset-4 hover:underline"
                      >
                        {i.description}
                      </button>
                    ) : (
                      i.description
                    )}
                  </TableCell>
                  <TableCell>{i.ownerName ?? '—'}</TableCell>
                  <TableCell>{fmtDate(i.dueDate)}</TableCell>
                  <TableCell>
                    <StatusBadge value={i.status} />
                  </TableCell>
                  <TableCell className="text-right">
                    <Button
                      variant="ghost"
                      size="icon"
                      aria-label="Delete action item"
                      onClick={() => remove(i.id)}
                    >
                      <Trash2 className="size-4" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}

// ── Risks ────────────────────────────────────────────────────────────
const RISK_LEVELS: RiskLevel[] = ['LOW', 'MEDIUM', 'HIGH'];
const RISK_STATUSES: RiskStatus[] = ['OPEN', 'MITIGATED', 'CLOSED'];

function RisksSection({
  kickoff,
  onChanged,
}: {
  kickoff: ProjectKickoff;
  onChanged: () => void;
}) {
  const toast = useToast();
  const confirm = useConfirm();
  const [adding, setAdding] = useState(false);
  const [form, setForm] = useState({
    description: '',
    likelihood: 'MEDIUM' as RiskLevel,
    impact: 'MEDIUM' as RiskLevel,
    mitigationPlan: '',
  });
  const [busy, setBusy] = useState(false);
  const risks = kickoff.risks ?? [];

  async function add() {
    if (!form.description.trim()) return;
    setBusy(true);
    try {
      await addRisk(kickoff.id, {
        description: form.description.trim(),
        likelihood: form.likelihood,
        impact: form.impact,
        mitigationPlan: form.mitigationPlan.trim() || undefined,
      });
      setForm({ description: '', likelihood: 'MEDIUM', impact: 'MEDIUM', mitigationPlan: '' });
      setAdding(false);
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Failed to add.');
    } finally {
      setBusy(false);
    }
  }

  async function setStatus(riskId: string, status: RiskStatus) {
    try {
      await updateRisk(kickoff.id, riskId, { status });
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Update failed.');
    }
  }

  async function remove(riskId: string) {
    if (
      !(await confirm({
        title: 'Delete risk?',
        confirmLabel: 'Delete',
        destructive: true,
      }))
    )
      return;
    try {
      await removeRisk(kickoff.id, riskId);
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Delete failed.');
    }
  }

  return (
    <Card className="mb-4">
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <CardTitle>Risk Register</CardTitle>
        <Button size="sm" variant="outline" onClick={() => setAdding((v) => !v)}>
          <Plus className="size-4" /> Add
        </Button>
      </CardHeader>
      <CardContent className="pt-0">
        {adding && (
          <div className="mb-3 grid gap-2 rounded-md border p-3 sm:grid-cols-2">
            <Input
              placeholder="Risk description"
              value={form.description}
              onChange={(e) => setForm({ ...form, description: e.target.value })}
              className="sm:col-span-2"
            />
            <label className="flex items-center gap-2 text-sm">
              Likelihood
              <Select
                value={form.likelihood}
                onChange={(e) => setForm({ ...form, likelihood: e.target.value as RiskLevel })}
                className="h-8"
              >
                {RISK_LEVELS.map((l) => (
                  <option key={l} value={l}>
                    {l}
                  </option>
                ))}
              </Select>
            </label>
            <label className="flex items-center gap-2 text-sm">
              Impact
              <Select
                value={form.impact}
                onChange={(e) => setForm({ ...form, impact: e.target.value as RiskLevel })}
                className="h-8"
              >
                {RISK_LEVELS.map((l) => (
                  <option key={l} value={l}>
                    {l}
                  </option>
                ))}
              </Select>
            </label>
            <Input
              placeholder="Mitigation plan"
              value={form.mitigationPlan}
              onChange={(e) => setForm({ ...form, mitigationPlan: e.target.value })}
              className="sm:col-span-2"
            />
            <div className="sm:col-span-2">
              <Button size="sm" onClick={add} disabled={busy || !form.description.trim()}>
                Add risk
              </Button>
            </div>
          </div>
        )}
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Description</TableHead>
              <TableHead>Likelihood</TableHead>
              <TableHead>Impact</TableHead>
              <TableHead>Mitigation</TableHead>
              <TableHead>Owner</TableHead>
              <TableHead>Status</TableHead>
              <TableHead />
            </TableRow>
          </TableHeader>
          <TableBody>
            {risks.length === 0 ? (
              <TableRow>
                <TableCell colSpan={7} className="text-center text-muted-foreground">
                  No risks recorded.
                </TableCell>
              </TableRow>
            ) : (
              risks.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="font-medium">{r.description}</TableCell>
                  <TableCell>
                    <StatusBadge value={r.likelihood} />
                  </TableCell>
                  <TableCell>
                    <StatusBadge value={r.impact} />
                  </TableCell>
                  <TableCell>{r.mitigationPlan ?? '—'}</TableCell>
                  <TableCell>{r.ownerName ?? '—'}</TableCell>
                  <TableCell>
                    <Select
                      value={r.status}
                      onChange={(e) => setStatus(r.id, e.target.value as RiskStatus)}
                      className="h-8 w-32"
                    >
                      {RISK_STATUSES.map((s) => (
                        <option key={s} value={s}>
                          {s}
                        </option>
                      ))}
                    </Select>
                  </TableCell>
                  <TableCell className="text-right">
                    <Button
                      variant="ghost"
                      size="icon"
                      aria-label="Delete risk"
                      onClick={() => remove(r.id)}
                    >
                      <Trash2 className="size-4" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}

// ── Delivery classification (per order line item) ───────────────────
const DELIVERY_TYPES: DeliveryType[] = ['NPD', 'IN_HOUSE', 'VENDOR'];

function DeliveryClassificationSection({
  kickoff,
  onChanged,
}: {
  kickoff: ProjectKickoff;
  onChanged: () => void;
}) {
  const items = kickoff.deliveryItems ?? [];
  return (
    <Card className="mb-4">
      <CardHeader>
        <CardTitle>Delivery Classification</CardTitle>
      </CardHeader>
      <CardContent className="pt-0">
        {items.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No line items on the linked order.
          </p>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Product</TableHead>
                <TableHead className="text-right">Qty</TableHead>
                <TableHead>Delivery type</TableHead>
                <TableHead>Vendor details</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((li) => (
                <DeliveryRow
                  key={li.id}
                  kickoffId={kickoff.id}
                  item={li}
                  onChanged={onChanged}
                />
              ))}
            </TableBody>
          </Table>
        )}
      </CardContent>
    </Card>
  );
}

function DeliveryRow({
  kickoffId,
  item,
  onChanged,
}: {
  kickoffId: string;
  item: KickoffDeliveryItem;
  onChanged: () => void;
}) {
  const toast = useToast();
  // Local editable buffers for the vendor fields (committed on blur).
  const [vendorName, setVendorName] = useState(item.vendorName ?? '');
  const [vendorContact, setVendorContact] = useState(item.vendorContactInfo ?? '');
  const [vendorLead, setVendorLead] = useState(item.vendorExpectedLeadTime ?? '');
  const [nudge, setNudge] = useState<KickoffDeliveryItem | null>(null);
  const [busy, setBusy] = useState(false);

  // Re-sync buffers when the persisted values change (e.g. selecting IN_HOUSE
  // auto-fills vendorName server-side; without this the input would keep the
  // stale local value and not show the auto-filled default).
  useEffect(() => {
    setVendorName(item.vendorName ?? '');
    setVendorContact(item.vendorContactInfo ?? '');
    setVendorLead(item.vendorExpectedLeadTime ?? '');
  }, [item.vendorName, item.vendorContactInfo, item.vendorExpectedLeadTime]);

  // Vendor detail fields apply to VENDOR (manual entry) and IN_HOUSE (fixed
  // partner, auto-filled but editable). NPD has no vendor.
  const showVendorFields =
    item.deliveryType === 'VENDOR' || item.deliveryType === 'IN_HOUSE';
  const isInHouse = item.deliveryType === 'IN_HOUSE';

  async function setType(deliveryType: DeliveryType) {
    setBusy(true);
    try {
      await updateDeliveryItem(kickoffId, item.id, { deliveryType });
      onChanged();
      // Soft nudge: vendor-sourced items carry more schedule/quality risk.
      if (deliveryType === 'VENDOR') setNudge(item);
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Update failed.');
    } finally {
      setBusy(false);
    }
  }

  async function saveVendorField(patch: {
    vendorName?: string;
    vendorContactInfo?: string;
    vendorExpectedLeadTime?: string;
  }) {
    try {
      await updateDeliveryItem(kickoffId, item.id, patch);
      onChanged();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Update failed.');
    }
  }

  return (
    <>
      <TableRow>
        <TableCell>
          <div className="font-medium">{item.productName}</div>
          <div className="text-xs text-muted-foreground">SKU: {item.productSku}</div>
        </TableCell>
        <TableCell className="text-right align-top">{item.quantity}</TableCell>
        <TableCell className="align-top">
          <Select
            value={item.deliveryType ?? ''}
            onChange={(e) => setType(e.target.value as DeliveryType)}
            disabled={busy}
            className="h-8 w-36"
          >
            <option value="" disabled>
              Unclassified
            </option>
            {DELIVERY_TYPES.map((t) => (
              <option key={t} value={t}>
                {DELIVERY_TYPE_LABEL[t]}
              </option>
            ))}
          </Select>
        </TableCell>
        <TableCell className="align-top">
          {showVendorFields ? (
            <div className="space-y-2">
              <p className="text-xs text-muted-foreground">
                {isInHouse
                  ? 'In-house manufacturing partner (pre-filled — edit if a different internal facility applies).'
                  : 'Approved vendor list coming soon — enter vendor name manually for now.'}
              </p>
              <Input
                value={vendorName}
                onChange={(e) => setVendorName(e.target.value)}
                onBlur={() => {
                  if (vendorName !== (item.vendorName ?? ''))
                    void saveVendorField({ vendorName });
                }}
                placeholder="Vendor name"
                className="h-8"
              />
              <Input
                value={vendorContact}
                onChange={(e) => setVendorContact(e.target.value)}
                onBlur={() => {
                  if (vendorContact !== (item.vendorContactInfo ?? ''))
                    void saveVendorField({ vendorContactInfo: vendorContact });
                }}
                placeholder="Contact (name / phone / email)"
                className="h-8"
              />
              <Input
                value={vendorLead}
                onChange={(e) => setVendorLead(e.target.value)}
                onBlur={() => {
                  if (vendorLead !== (item.vendorExpectedLeadTime ?? ''))
                    void saveVendorField({ vendorExpectedLeadTime: vendorLead });
                }}
                placeholder="Expected lead time (e.g. 6–8 weeks)"
                className="h-8"
              />
            </div>
          ) : (
            <span className="text-sm text-muted-foreground">—</span>
          )}
        </TableCell>
      </TableRow>

      {nudge && (
        <VendorRiskNudge
          kickoffId={kickoffId}
          productName={nudge.productName}
          onClose={() => setNudge(null)}
          onAdded={() => {
            setNudge(null);
            onChanged();
          }}
        />
      )}
    </>
  );
}

/**
 * Soft nudge shown when a line item is marked Vendor: offers a pre-filled draft
 * risk (vendor-sourced items commonly carry more schedule/quality risk), which
 * the user can add or dismiss. The Risk Register already exists, so this is a
 * cheap prompt rather than relying on someone remembering.
 */
function VendorRiskNudge({
  kickoffId,
  productName,
  onClose,
  onAdded,
}: {
  kickoffId: string;
  productName: string;
  onClose: () => void;
  onAdded: () => void;
}) {
  const toast = useToast();
  const [description, setDescription] = useState(
    `Vendor-sourced delivery risk for ${productName}`,
  );
  const [busy, setBusy] = useState(false);

  async function add() {
    setBusy(true);
    try {
      await addRisk(kickoffId, {
        description: description.trim() || `Vendor-sourced delivery risk for ${productName}`,
        likelihood: 'MEDIUM',
        impact: 'MEDIUM',
      });
      toast.success('Risk added to the register.');
      onAdded();
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Failed to add risk.');
      setBusy(false);
    }
  }

  return (
    <Dialog open onOpenChange={(o) => !o && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Add a vendor delivery risk?</DialogTitle>
        </DialogHeader>
        <p className="text-sm text-muted-foreground">
          Vendor-sourced items often carry more schedule and quality risk than
          in-house production. Add a risk to the register now, or dismiss.
        </p>
        <Input
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          className="mt-2"
        />
        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={busy}>
            Dismiss
          </Button>
          <Button onClick={add} disabled={busy}>
            {busy ? 'Adding…' : 'Add risk'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ── Minutes / notes ──────────────────────────────────────────────────
function MinutesSection({
  kickoff,
  onSaved,
}: {
  kickoff: ProjectKickoff;
  onSaved: (k: ProjectKickoff) => void;
}) {
  const toast = useToast();
  const [text, setText] = useState(kickoff.minutesNotes ?? '');
  const [saving, setSaving] = useState(false);
  const dirty = text !== (kickoff.minutesNotes ?? '');

  async function save() {
    setSaving(true);
    try {
      const updated = await updateKickoff(kickoff.id, { minutesNotes: text || null });
      onSaved(updated);
      toast.success('Notes saved.');
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Save failed.');
    } finally {
      setSaving(false);
    }
  }

  return (
    <Card className="mb-4">
      <CardHeader>
        <CardTitle>Minutes &amp; Notes</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3 pt-0">
        <Textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          rows={4}
          placeholder="Anything not captured in the structured sections above…"
        />
        {dirty && (
          <Button size="sm" onClick={save} disabled={saving}>
            {saving ? 'Saving…' : 'Save'}
          </Button>
        )}
      </CardContent>
    </Card>
  );
}
