ALTER TYPE "NotificationType" ADD VALUE 'QMS_ACTION_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE 'QMS_ACTION_OVERDUE';
CREATE TYPE "QmsNcrSource" AS ENUM ('INSPECTION','GRN','AUDIT','CUSTOMER_COMPLAINT','CALIBRATION','MANUAL');
CREATE TYPE "QmsNcrSeverity" AS ENUM ('CRITICAL','MAJOR','MINOR');
CREATE TYPE "QmsNcrStatus" AS ENUM ('OPEN','CONTAINED','INVESTIGATION','PENDING_DISPOSITION','CAPA_IN_PROGRESS','VERIFICATION','CLOSED','CANCELLED');
CREATE TYPE "QmsDisposition" AS ENUM ('REWORK','REPAIR','USE_AS_IS','RETURN_TO_SUPPLIER','SCRAP','CONCESSION');
CREATE TYPE "QmsCapaStatus" AS ENUM ('DRAFT','IN_PROGRESS','PENDING_EFFECTIVENESS','EFFECTIVE','INEFFECTIVE','CLOSED');
CREATE TYPE "QmsCapaActionStatus" AS ENUM ('OPEN','IN_PROGRESS','COMPLETED','VERIFIED','CANCELLED');
CREATE TABLE "qms_non_conformances" ("id" TEXT NOT NULL,"ncrNumber" TEXT NOT NULL,"source" "QmsNcrSource" NOT NULL,"sourceId" TEXT,"legacyStoreNcrId" TEXT,"inspectionId" TEXT,"severity" "QmsNcrSeverity" NOT NULL,"status" "QmsNcrStatus" NOT NULL DEFAULT 'OPEN',"title" TEXT NOT NULL,"description" TEXT NOT NULL,"requirement" TEXT,"actualResult" TEXT,"productId" TEXT,"orderId" TEXT,"projectKickoffId" TEXT,"grnId" TEXT,"itemId" TEXT,"batchOrSerial" TEXT,"affectedQuantity" DECIMAL(14,4),"costOfPoorQuality" DECIMAL(18,2),"containmentAction" TEXT,"containedAt" TIMESTAMP(3),"disposition" "QmsDisposition","dispositionNotes" TEXT,"concessionRequired" BOOLEAN NOT NULL DEFAULT false,"ownerId" TEXT NOT NULL,"targetDate" TIMESTAMP(3) NOT NULL,"raisedById" TEXT NOT NULL,"dispositionedById" TEXT,"dispositionedAt" TIMESTAMP(3),"closedById" TEXT,"closedAt" TIMESTAMP(3),"closureNote" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "qms_non_conformances_pkey" PRIMARY KEY ("id"));
CREATE TABLE "qms_capas" ("id" TEXT NOT NULL,"capaNumber" TEXT NOT NULL,"ncrId" TEXT NOT NULL,"status" "QmsCapaStatus" NOT NULL DEFAULT 'DRAFT',"problemStatement" TEXT NOT NULL,"rootCauseMethod" TEXT,"rootCauseAnalysis" JSONB,"rootCauseConclusion" TEXT,"correction" TEXT,"effectivenessCriteria" TEXT,"effectivenessDueDate" TIMESTAMP(3),"effectivenessResult" TEXT,"effectivenessReviewedById" TEXT,"effectivenessReviewedAt" TIMESTAMP(3),"ownerId" TEXT NOT NULL,"createdById" TEXT NOT NULL,"closedById" TEXT,"closedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "qms_capas_pkey" PRIMARY KEY ("id"));
CREATE TABLE "qms_capa_actions" ("id" TEXT NOT NULL,"capaId" TEXT NOT NULL,"actionType" TEXT NOT NULL,"description" TEXT NOT NULL,"ownerId" TEXT NOT NULL,"dueDate" TIMESTAMP(3) NOT NULL,"status" "QmsCapaActionStatus" NOT NULL DEFAULT 'OPEN',"completionNote" TEXT,"evidence" JSONB,"completedById" TEXT,"completedAt" TIMESTAMP(3),"verifiedById" TEXT,"verifiedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "qms_capa_actions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "qms_non_conformances_ncrNumber_key" ON "qms_non_conformances"("ncrNumber");
CREATE UNIQUE INDEX "qms_non_conformances_legacyStoreNcrId_key" ON "qms_non_conformances"("legacyStoreNcrId");
CREATE INDEX "qms_non_conformances_status_targetDate_idx" ON "qms_non_conformances"("status","targetDate");
CREATE INDEX "qms_non_conformances_severity_status_idx" ON "qms_non_conformances"("severity","status");
CREATE INDEX "qms_non_conformances_inspectionId_idx" ON "qms_non_conformances"("inspectionId");
CREATE UNIQUE INDEX "qms_capas_capaNumber_key" ON "qms_capas"("capaNumber");
CREATE UNIQUE INDEX "qms_capas_ncrId_key" ON "qms_capas"("ncrId");
CREATE INDEX "qms_capas_status_effectivenessDueDate_idx" ON "qms_capas"("status","effectivenessDueDate");
CREATE INDEX "qms_capa_actions_ownerId_status_dueDate_idx" ON "qms_capa_actions"("ownerId","status","dueDate");
CREATE INDEX "qms_capa_actions_capaId_status_idx" ON "qms_capa_actions"("capaId","status");
ALTER TABLE "qms_non_conformances" ADD CONSTRAINT "qms_non_conformances_inspectionId_fkey" FOREIGN KEY ("inspectionId") REFERENCES "qms_inspections"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "qms_capas" ADD CONSTRAINT "qms_capas_ncrId_fkey" FOREIGN KEY ("ncrId") REFERENCES "qms_non_conformances"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "qms_capa_actions" ADD CONSTRAINT "qms_capa_actions_capaId_fkey" FOREIGN KEY ("capaId") REFERENCES "qms_capas"("id") ON DELETE CASCADE ON UPDATE CASCADE;
