ALTER TABLE "employees" ADD COLUMN "isDesignHead" BOOLEAN NOT NULL DEFAULT false;
CREATE TYPE "DesignRequestStatus" AS ENUM ('OPEN','ACCEPTED','REJECTED','CONVERTED','CLOSED');
CREATE TYPE "DesignRequestSource" AS ENUM ('SALES_ORDER','PROJECT_KICKOFF','CUSTOMER_CHANGE','INTERNAL_DEVELOPMENT','NCR_CAPA','VALUE_ENGINEERING');
CREATE TYPE "DesignPriority" AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE "DesignProjectStatus" AS ENUM ('REQUIREMENTS','CONCEPT','DETAILED_DESIGN','INTERNAL_REVIEW','CUSTOMER_APPROVAL','RELEASED_FOR_PRODUCTION','ON_HOLD','CLOSED');
CREATE TYPE "DesignDocumentType" AS ENUM ('GENERAL_ARRANGEMENT','MANUFACTURING_DRAWING','ASSEMBLY_DRAWING','ELECTRICAL_DRAWING','SCHEMATIC','CALCULATION','DATASHEET','SPECIFICATION','THREE_D_MODEL','WORK_INSTRUCTION','OTHER');
CREATE TYPE "DesignRevisionStatus" AS ENUM ('DRAFT','PENDING_APPROVAL','RELEASED','REJECTED','OBSOLETE');
CREATE TABLE "design_requests" ("id" TEXT NOT NULL,"requestNumber" TEXT NOT NULL,"source" "DesignRequestSource" NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"priority" "DesignPriority" NOT NULL DEFAULT 'MEDIUM',"status" "DesignRequestStatus" NOT NULL DEFAULT 'OPEN',"productId" TEXT,"customerId" TEXT,"orderId" TEXT,"projectKickoffId" TEXT,"requestedById" TEXT NOT NULL,"ownerId" TEXT,"targetDate" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "design_requests_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "design_requests_requestNumber_key" ON "design_requests"("requestNumber");
CREATE INDEX "design_requests_status_targetDate_idx" ON "design_requests"("status","targetDate");
CREATE INDEX "design_requests_ownerId_status_idx" ON "design_requests"("ownerId","status");
CREATE TABLE "design_projects" ("id" TEXT NOT NULL,"projectNumber" TEXT NOT NULL,"requestId" TEXT,"name" TEXT NOT NULL,"description" TEXT,"status" "DesignProjectStatus" NOT NULL DEFAULT 'REQUIREMENTS',"productId" TEXT,"customerId" TEXT,"orderId" TEXT,"projectKickoffId" TEXT,"leadDesignerId" TEXT NOT NULL,"targetDate" TIMESTAMP(3) NOT NULL,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "design_projects_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "design_projects_projectNumber_key" ON "design_projects"("projectNumber");
CREATE UNIQUE INDEX "design_projects_requestId_key" ON "design_projects"("requestId");
CREATE INDEX "design_projects_status_targetDate_idx" ON "design_projects"("status","targetDate");
CREATE INDEX "design_projects_leadDesignerId_status_idx" ON "design_projects"("leadDesignerId","status");
CREATE TABLE "design_documents" ("id" TEXT NOT NULL,"documentNumber" TEXT NOT NULL,"projectId" TEXT NOT NULL,"title" TEXT NOT NULL,"documentType" "DesignDocumentType" NOT NULL,"vaultFileId" TEXT NOT NULL,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "design_documents_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "design_documents_documentNumber_key" ON "design_documents"("documentNumber");
CREATE INDEX "design_documents_projectId_documentType_idx" ON "design_documents"("projectId","documentType");
CREATE INDEX "design_documents_vaultFileId_idx" ON "design_documents"("vaultFileId");
CREATE TABLE "design_document_revisions" ("id" TEXT NOT NULL,"documentId" TEXT NOT NULL,"revisionNumber" INTEGER NOT NULL,"revisionCode" TEXT NOT NULL,"status" "DesignRevisionStatus" NOT NULL DEFAULT 'DRAFT',"changeSummary" TEXT NOT NULL,"vaultFileVersionId" TEXT NOT NULL,"preparedById" TEXT NOT NULL,"submittedById" TEXT,"submittedAt" TIMESTAMP(3),"approvedById" TEXT,"approvedAt" TIMESTAMP(3),"approverNameSnapshot" TEXT,"signatureTextSnapshot" TEXT,"signatureFontSnapshot" "SignatureFont","rejectionReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "design_document_revisions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "design_document_revisions_documentId_revisionNumber_key" ON "design_document_revisions"("documentId","revisionNumber");
CREATE UNIQUE INDEX "design_document_revisions_documentId_revisionCode_key" ON "design_document_revisions"("documentId","revisionCode");
CREATE INDEX "design_document_revisions_status_submittedAt_idx" ON "design_document_revisions"("status","submittedAt");
CREATE INDEX "design_document_revisions_vaultFileVersionId_idx" ON "design_document_revisions"("vaultFileVersionId");
ALTER TABLE "design_projects" ADD CONSTRAINT "design_projects_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "design_requests"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "design_documents" ADD CONSTRAINT "design_documents_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "design_projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "design_documents" ADD CONSTRAINT "design_documents_vaultFileId_fkey" FOREIGN KEY ("vaultFileId") REFERENCES "vault_files"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "design_document_revisions" ADD CONSTRAINT "design_document_revisions_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "design_documents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "design_document_revisions" ADD CONSTRAINT "design_document_revisions_vaultFileVersionId_fkey" FOREIGN KEY ("vaultFileVersionId") REFERENCES "vault_file_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
