import {
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { KanbanCardStatus } from '@prisma/client';
import { PrismaService } from '../../core/database/prisma.service';
import { AuthenticatedUser } from '../../common/decorators/current-user.decorator';
import { KanbanAccessService } from './kanban-access.service';
import { KanbanNotificationsService } from '../notifications/kanban-notifications.service';
import { CreateCommentDto } from './dto/kanban.dto';
import {
  KanbanCommentEntity,
  KanbanFeedItemEntity,
} from './entities/kanban.entity';

/**
 * Card comments + the combined comment/activity feed. Comments are user-
 * authored; activity is system-generated by KanbanCardsService. This service
 * owns the read side (list/feed) and comment write/delete; activity is never
 * created here (no endpoint for it).
 */
@Injectable()
export class KanbanFeedService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly access: KanbanAccessService,
    private readonly notifications: KanbanNotificationsService,
  ) {}

  /**
   * Add a comment — any board member, OR (card-only access) the card's own
   * assignee. Notifies the card's assignee.
   */
  async addComment(
    cardId: string,
    dto: CreateCommentDto,
    user: AuthenticatedUser,
  ): Promise<KanbanCommentEntity> {
    const card = await this.getCardOrThrow(cardId);
    await this.access.assertCanEditCard(user, card.boardId, card.assigneeId);
    const comment = await this.prisma.kanbanCardComment.create({
      data: { cardId, authorId: user.id, text: dto.text },
      include: { author: { select: { firstName: true, lastName: true } } },
    });
    // Notify the current assignee (skipped if they authored the comment).
    await this.notifications.notifyCommented({
      assigneeId: card.assigneeId,
      actorId: user.id,
      cardId,
      cardTitle: card.title,
    });
    return this.toCommentEntity(comment);
  }

  /**
   * Delete a comment — the AUTHOR, or a Scrum Master/SUPER_ADMIN who manages
   * the board (same override pattern as Phase 2's card-delete). Not any member.
   */
  async deleteComment(
    cardId: string,
    commentId: string,
    user: AuthenticatedUser,
  ): Promise<void> {
    const card = await this.getCardOrThrow(cardId);
    await this.access.assertCanEditCard(user, card.boardId, card.assigneeId);
    const comment = await this.prisma.kanbanCardComment.findUnique({
      where: { id: commentId },
    });
    if (!comment || comment.cardId !== cardId) {
      throw new NotFoundException('Comment not found');
    }
    const isAuthor = comment.authorId === user.id;
    const canManage = await this.access
      .assertCanManageBoard(user, card.boardId)
      .then(() => true)
      .catch(() => false);
    if (!isAuthor && !canManage) {
      throw new ForbiddenException(
        'Only the comment author or a Scrum Master/SUPER_ADMIN may delete this comment',
      );
    }
    await this.prisma.kanbanCardComment.delete({ where: { id: commentId } });
  }

  /**
   * Combined feed: comments + activity merged chronologically (oldest→newest),
   * each tagged COMMENT or ACTIVITY so the UI can render them differently.
   * Any board member, OR (card-only access) the card's own assignee.
   */
  async getFeed(
    cardId: string,
    user: AuthenticatedUser,
  ): Promise<KanbanFeedItemEntity[]> {
    const card = await this.getCardOrThrow(cardId);
    await this.access.assertCanViewCard(user, card.boardId, card.assigneeId);

    const [comments, activity] = await Promise.all([
      this.prisma.kanbanCardComment.findMany({
        where: { cardId },
        include: { author: { select: { firstName: true, lastName: true } } },
      }),
      this.prisma.kanbanCardActivity.findMany({
        where: { cardId },
        include: { actor: { select: { firstName: true, lastName: true } } },
      }),
    ]);

    const items: KanbanFeedItemEntity[] = [
      ...comments.map(
        (c) =>
          new KanbanFeedItemEntity({
            kind: 'COMMENT',
            id: c.id,
            actorId: c.authorId,
            actorName: c.author
              ? `${c.author.firstName} ${c.author.lastName}`
              : null,
            text: c.text,
            createdAt: c.createdAt.toISOString(),
          }),
      ),
      ...activity.map(
        (a) =>
          new KanbanFeedItemEntity({
            kind: 'ACTIVITY',
            id: a.id,
            actorId: a.actorId,
            actorName: a.actor
              ? `${a.actor.firstName} ${a.actor.lastName}`
              : null,
            text: a.description,
            createdAt: a.createdAt.toISOString(),
          }),
      ),
    ];
    items.sort((x, y) => x.createdAt.localeCompare(y.createdAt));
    return items;
  }

  // ── internals ──────────────────────────────────────────────────────

  private async getCardOrThrow(id: string): Promise<{
    id: string;
    boardId: string;
    assigneeId: string | null;
    title: string;
  }> {
    const card = await this.prisma.kanbanCard.findUnique({
      where: { id },
      select: {
        id: true,
        status: true,
        title: true,
        assigneeId: true,
        list: { select: { boardId: true } },
      },
    });
    if (!card || card.status === KanbanCardStatus.ARCHIVED) {
      throw new NotFoundException('Card not found');
    }
    return {
      id: card.id,
      boardId: card.list.boardId,
      assigneeId: card.assigneeId,
      title: card.title,
    };
  }

  private toCommentEntity(c: {
    id: string;
    cardId: string;
    authorId: string;
    text: string;
    createdAt: Date;
    author: { firstName: string; lastName: string } | null;
  }): KanbanCommentEntity {
    return new KanbanCommentEntity({
      id: c.id,
      cardId: c.cardId,
      authorId: c.authorId,
      authorName: c.author
        ? `${c.author.firstName} ${c.author.lastName}`
        : null,
      text: c.text,
      createdAt: c.createdAt.toISOString(),
    });
  }
}
